### PR TITLE
travis: update go version

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by rjeczalik** [comment]
Hey @dvrkps! Since we're at it, could you please remove [this line](https://github.com/rjeczalik/ciexec/blob/master/.travis.yml#L15) and the same for appveyor?

**Comment by dvrkps** [comment]
@rjeczalik ping :)

appveyor: bash\bash.go:28:12: undefined: pty.Start

**Comment by rjeczalik** [comment]
Hey @dvrkps! Mea culpa, I must have missed notification for this PR. Thanks!

And yeah, it'd need some extra work to make it build on Windows.

**Comment by dvrkps** [comment]
@rjeczalik np. Cheers.

**Pull request merged**
